charts/metal-control-plane/Chart.yaml
charts/metal-control-plane/templates/metal-api.yaml

Prevents jobs from queuing up unnecessarily.

Use replace concurrency policy for metal-api cron jobs.

---

charts/metal-control-plane/templates/metal-api.yaml

Let only the init-db hook do the job.
References https://github.com/metal-stack/metal-api/pull/156.
Closes #9.

Don't init data store with metal-api instances.

---

README.md

Add the missing protocol to the special pull requests URL, just in case someone else tries to copy & paste it when using it the first time :-)

Add missing protocol to pull request URL

---

charts/metal-control-plane/Chart.yaml
charts/metal-control-plane/templates/masterdata-api-config.yaml
charts/metal-control-plane/templates/masterdata-api.yaml

With this approach we make the masterdata-api only restart if configuration relevant for this component changes and not when there is a change in the rest of the config, too.

Only restart masterdata-api when relevant configuration changes.

---

charts/postgreslet/Chart.yaml
charts/postgreslet/templates/configmap.yaml

This reverts commit 4c323c5431e8eedcb7ffe3d4e061dda15045ef6d.
Using the helper variable again, as it falls back to the helm release name if that `customPspName` is not set.
This caused some troubles as the operator falls back to the default psp name, which was present on shared clusters where the operator was installed manually or via ansible, but was not present where the postgreslet was insatlled via this helm chart (as it installs that psp under another name).

Revert "Fix variable in template"

---

charts/postgreslet/Chart.yaml
charts/postgreslet/crds/postgresql.yaml
charts/postgreslet/templates/configmap.yaml
charts/postgreslet/values.yaml

* Update the CRD for use with the (forked) postgres-operator image
* Use the new images by default (can still be overridden)
* Add a config options required for the use with the new operator image (and two others too)

Custom CRD for standby clusters and additional params

---

charts/postgreslet/Chart.yaml
charts/postgreslet/values.yaml

The definition of the image vector became qute cumbersome in all our installations.
To simplify things, I want to define the all versions in the postgreslet helm chart and keep that one updated.

Postgreslet version pinning

---

charts/csi-driver-lvm/Chart.yaml
charts/csi-driver-lvm/templates/plugin.yaml

Hi, the `name` filed was used twice.
Therefore I got an error when using your chart with kustomize.
Removing the second name field of the `node-driver-registrar` container allowed me to use your chart with kustomize.
Could you please merge?

The name field was used twice, therefore I got an error in kustomize.

---

charts/metal-control-plane/Chart.yaml
charts/metal-control-plane/templates/metal-api.yaml

enables a more graceful rollingUpdate

add readinessProbe to metal-api deployment

---

charts/csi-driver-lvm/Chart.yaml
charts/csi-driver-lvm/templates/plugin.yaml
charts/csi-driver-lvm/values.yaml

Resolves https://github.com/metal-stack/csi-driver-lvm/issues/86
`/etc` on Talos OS is read-only, which means that this chart will fail to install as is. The new `hostWritePath` option allows the default `/etc/lvm` to be overwritten. For Talos OS, setting `hostWritePath: /var/etc/lvm` fixes the install issue. This is just half the story.
After this installs, creating a PVs will fail since the controller has some hard-coded paths starting with `/etc`. Here is the second half of this fix: https://github.com/metal-stack/csi-driver-lvm/pull/87
First step is to get that PR 👆 merged first, then update the image versions in this one before merging this change.
---
Learn more about the Talos' file system: https://www.talos.dev/v1.4/learn-more/architecture/

Add support for Talos OS

---

charts/csi-driver-lvm/Chart.yaml
charts/csi-driver-lvm/templates/plugin.yaml
charts/csi-driver-lvm/values.yaml

Mirror the controller nodeSelector settings for plugins.
Useful if one wants to deploy the CSI plugins to only a subset of nodes

feat(csi-driver-lvm): allow nodeSelector for plugin DaemonSet

---

charts/postgreslet/Chart.yaml
charts/postgreslet/templates/configmap-sidecars.yaml
charts/postgreslet/values.yaml

After disabling it for performance reasons, it was now decided to make it configurable for certain partitions.
To prevent duplicate definitions of exporter queries, this is handled directly in the chart (and not by overriding the value during the deployment of the chart for example)

Postgres: Make pg_stat_statements configurable

---

charts/postgreslet/Chart.yaml
charts/postgreslet/values.yaml

This PR replaces https://github.com/metal-stack/helm-charts/pull/87 by using a new branch directly instead of a fork. It also bumps the postgreslet chart version to `0.13.1`.

add queryid to avoid duplicate rows error which leads to exporter crash

---

charts/csi-driver-lvm/Chart.yaml
charts/csi-driver-lvm/templates/plugin.yaml

Currently --kubelet-registration-path parameter of node-driver-registrar container from csi-driver-lvm-plugin daemonSet points to the directory which is not mounted.
Found this out when tried to run all csi-driver-lvm containers with readOnlyRootFilesystem securityContext set to "true".

Fix mount for node-driver-registrar

---

charts/csi-driver-lvm/Chart.yaml
charts/csi-driver-lvm/templates/controller.yaml
charts/csi-driver-lvm/templates/plugin.yaml

Hardcode readOnlyRootFilesystem set to true for all containers as a general security measure.
Host paths and volumes where rw access is needed should be mounted explicitly.
A followup of https://github.com/metal-stack/helm-charts/pull/65 and https://github.com/metal-stack/helm-charts/issues/66

Set readOnlyRootFilesystem: true for all containers

---

charts/csi-driver-lvm/Chart.yaml
charts/csi-driver-lvm/templates/plugin.yaml

Regression of https://github.com/metal-stack/helm-charts/pull/67.
```
E0924 11:25:04.026502       1 server.go:114] GRPC error: unable to create lv: exit status 5 output:  Creating logical volume csi-d3f9243895aa3b4fa14390986b1996671cdd5d6cf8409ba558d570714d6e18e1
Cannot archive volume group metadata for csi-lvm to read-only filesystem.
```

Add missing mount of lvm archive directory.

---

charts/metal-control-plane/Chart.yaml
charts/metal-control-plane/templates/metal-api.yaml
charts/metal-control-plane/values.yaml

References:
- https://github.com/metal-stack/metal-roles/pull/322
-  metal-stack/metal-api#576

Adapt to latest size reservations API.

---

charts/metal-control-plane/Chart.yaml
charts/metal-control-plane/templates/ipam.yaml
charts/metal-control-plane/values.yaml

By default the ipam deployment has two `Replicas` and the `PodDisruptionBudget` `minAvailable` property is set to two. This prevents disruptions, when performing Kubernetes operation updates.
This PR defaults `minAvailable` property to one and makes it configurable.

Default PDB minAvailable to one and make it configurable

---

charts/postgreslet/values.yaml

Add two more monitoring metrics to postgreslet deployment queries.yaml:
- `pg_sync_standby_nominal_actual`: show if nominal and actual sync standbys, if any, are matching, becomes critical when nominal!=actual
- `pg_replication_blocked_transactions`: show the number of transactions blocked by one or more defect sync standbys
These two additional metrics fix the following problem: every once in a while a sync standby in another DC fails (for whatever reason). Now if someone issues a write transaction on the primary (e.g. insert, update or delete), then this query will hang (forever or until some timeout). On a high load instance the apps using the database will after some time get stuck and in the end the whole system stands still.
However, currently we do not have any means to monitor …

add pg_sync_standby_nominal_actual and pg_replication_blocked_transactions

---

charts/postgreslet/values.yaml

Latest image has errors when trying to do sync replication, so rollback to old image

rollback spilo image

---

charts/postgreslet/Chart.yaml
charts/postgreslet/values.yaml

Going back to using the 3.2 spilo image, but with updated postgresql packages. This is neccessary because the updated wal-g in the newer spilo image changed the output of the cli, which breaks the cleanup of old backups.
Also fix the `appVersion` of the chart to match the actual postgreslet version.
This does not (yet) contain the updated spilo images for `CVE-2025-1094`.

Postgreslet update spilo image

---

charts/valkey/.helmignore
charts/valkey/Chart.yaml
charts/valkey/templates/NOTES.txt
charts/valkey/templates/_helpers.tpl
charts/valkey/templates/configmap.yaml
charts/valkey/templates/service.yaml
charts/valkey/templates/serviceaccount.yaml
charts/valkey/templates/statefulset.yaml
charts/valkey/values.yaml

Created Helm Chart for Valkey, because the modification of the original Bitnami-Chart is too complex in comparison.
Used tutorial https://blog.enapi.com/valkey-clusters-in-kubernetes-a-comprehensive-guide-94994d0a8ebb for help.
The current version is mainly for testing purposes. Therefore, it has a switch, whether to use it in cluster-mode with the specified amount of instances or in single mode with one instance.
In cluster-mode, there is still an issue, that requires to run redis-cli --cluster fix <host>:<port> to reassign the slots before the cluster is usable. Need help to fix this.
Therefore, only the single-mode is supported yet, but should be fine for testing purposes.
References https://github.com/metal-stack/releases/issues/249.

Add valkey chart to remove dependency from bitnami
